# spring-redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 1000
  application:
    name: cache-redis-boot-sample

# 应用port
server:
  port: 10089


# 日志配置
logging:
  level:
    zen.hua.cache.redis: debug
    redis.boot.sample.t1_base: trace
  #  控制台日志输出格式
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n"