package dao;

import java.util.List;
import model.TabJsonDO;
import model.TabJsonDOExample;
import org.apache.ibatis.annotations.Param;

public interface TabJsonDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    long countByExample(TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int deleteByExample(TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int insert(TabJsonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int insertSelective(TabJsonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    List<TabJsonDO> selectByExampleWithBLOBs(TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    List<TabJsonDO> selectByExample(TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    TabJsonDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TabJsonDO record, @Param("example") TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TabJsonDO record, @Param("example") TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TabJsonDO record, @Param("example") TabJsonDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TabJsonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_json
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TabJsonDO record);
}